---
name: 'npm publish action'
description: 'Publishes npm packages using snapshot versioning'

outputs:
  name:
    description: 'The name of the npm package which was published'
    value: ${{ steps.publish.outputs.name }}
  version:
    description: 'The version of the npm package which was published'
    value: ${{ steps.publish.outputs.version }}

runs:
  using: composite
  steps:

    - name: Check preconditions
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/check-preconditions.sh

    - name: Set SNAPSHOT version
      if: startsWith(github.ref, 'refs/heads')
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/set-snapshot-version.sh

    - name: Set RELEASE version
      if: startsWith(github.ref, 'refs/tags')
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/set-release-version.sh

    - name: Publish npm package
      id: 'publish'
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/publish.sh
